version: "3"
services:
  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: react-container
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  seller-dashboard:
    build:
      context: "./seller-dashboard"
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    container_name: seller-react-container
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-network
    volumes:
      - ./seller-dashboard:/app
      - /app/node_modules
    depends_on:
      - backend
  admin-dashboard:
    build:
      context: "./admin-dashboard"
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    container_name: admin-react-container
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-network
    volumes:
      - ./admin-dashboard:/app
      - /app/node_modules
    depends_on:
      - backend
  ticket-master-dashboard:
    build:
      context: "./ticket-master-dashboard"
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    container_name: ticket-master-react-container
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-network
    volumes:
      - ./ticket-master-dashboard:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - 5500:5500
    container_name: express-container
    networks:
      - mern-stack-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
    restart: always
  mongo:
    build:
      context: .
      dockerfile: ./mongodb/mongodb.dockerfile
    restart: always
    networks:
      - mern-stack-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - type: bind
        source: ./data
        target: /data/db
      - mongo-data:/data/db
      - mongo-logs:/var/log/mongodb
    ports:
      - "27017:27017"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
networks:
  mern-stack-network:
volumes:
  mongo-data:
  mongo-logs:
